/**
 * Optional TypeScript shapes for tree-sitter CLI artifacts under `parser/abl/src/`.
 * Regenerated by `tree-sitter generate` (not hand-edited). `grammar.json` may be
 * empty until generate is run; `node-types.json` is populated from upstream sync.
 */

export interface GrammarTypeRef {
  type: string;
  named: boolean;
}

export interface GrammarFieldSpec {
  multiple: boolean;
  required: boolean;
  types: GrammarTypeRef[];
}

export interface GrammarChildrenSpec {
  multiple: boolean;
  required: boolean;
  types: GrammarTypeRef[];
}

/** One entry in `node-types.json` (array of node descriptors). */
export interface NodeTypeDescriptor {
  type: string;
  named: boolean;
  subtypes?: GrammarTypeRef[];
  fields?: Record<string, GrammarFieldSpec>;
  children?: GrammarChildrenSpec;
}

export type NodeTypesJson = NodeTypeDescriptor[];

/**
 * Subset of `grammar.json` emitted by tree-sitter generate.
 * Full schema varies by CLI version; extend as needed when regenerating locally.
 */
export interface GrammarJson {
  name?: string;
  word?: string;
  rules?: Record<string, unknown>;
  extras?: unknown[];
  externals?: unknown[];
  conflicts?: string[][];
  precedences?: string[][];
  supertypes?: Record<string, string[]>;
  inline?: string[];
  [key: string]: unknown;
}

declare module "./grammar.json" {
  const value: GrammarJson;
  export default value;
}

declare module "./node-types.json" {
  const value: NodeTypesJson;
  export default value;
}
